# Testing the data pre-processing part for the Informer

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
variant = "2023"
dataset_dir = "/lcrc/group/ATLAS/users/jhoya/DAQ/atlas-hlt-datasets/"
train_set_x_df = pd.read_csv(f'{dataset_dir}/train_set_'\
                                    f'dcm_rates_{variant}.csv', index_col=0)
test_set_x_df = pd.read_csv(f'{dataset_dir}/test_set_'\
                                    f'dcm_rates_{variant}.csv', index_col=0)
val_set_x_df = pd.read_csv(f'{dataset_dir}/val_set_'\
                                    f'dcm_rates_{variant}.csv', index_col=0)

In [3]:
train_set_x_df.describe()

,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55002.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55003.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55004.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55005.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55006.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55007.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55008.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55009.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55010.info,DF_IS:HLT-24:tpu-rack-55.DCM:HLT-24:tpu-rack-55:pc-tdq-tpu-55011.info,...,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91031.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91032.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91033.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91034.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91035.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91036.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91037.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91038.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91039.info,DF_IS:HLT-32_48:tpu-rack-91.DCM:HLT-32_48:tpu-rack-91:pc-tdq-tpu-91040.info
count,56890.000000,56885.000000,56885.000000,56886.000000,56884.000000,56885.000000,56884.000000,25090.000000,56885.000000,56885.000000,...,56885.000000,56884.000000,56885.000000,56886.000000,56884.000000,56886.000000,56886.000000,56884.000000,56885.000000,56885.000000
mean,11.687301,11.643969,11.711244,11.672377,11.684181,11.703433,11.683918,11.404893,11.417263,11.690095,...,25.737556,25.780685,25.672399,25.743871,25.767604,25.732391,25.671564,25.744659,25.758603,25.729936
std,3.630157,3.601160,3.638891,3.615478,3.628698,3.636288,3.620449,3.719789,3.427351,3.631370,...,8.658371,8.686826,8.600509,8.668223,8.678113,8.643136,8.605270,8.686976,8.663617,8.651950
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.600021,9.599991,9.600003,9.600000,9.600002,9.600002,9.600001,9.600008,9.600004,9.600006,...,19.200157,19.200166,19.200146,19.200160,19.200181,19.200151,19.200166,19.200146,19.200153,19.200191
50%,11.999982,11.998148,12.000026,11.999932,11.999918,11.999980,11.999984,11.600060,11.796601,11.999960,...,26.409235,26.598076,26.400188,26.588094,26.599843,26.411382,26.400353,26.599808,26.599841,26.593835
75%,14.199947,14.000224,14.199954,14.199808,14.199820,14.199963,14.199859,13.800063,13.600308,14.199891,...,32.601125,32.799985,32.599720,32.602734,32.799939,32.615360,32.599817,32.617348,32.782544,32.616602
max,31.200335,30.396222,31.398970,32.997573,41.799594,33.798203,32.799035,29.400722,33.196233,45.597744,...,50.385305,51.192323,52.797258,50.956589,53.332486,50.566331,52.555376,52.978151,55.333550,49.590485

In [4]:
#test_set_x_df
#val_set_x_df
print(f'Train set size: {len(train_set_x_df)}')
print(f'Test set size: {len(test_set_x_df)}')
print(f'Val set size: {len(val_set_x_df)}')

Train set size: 56890
Test set size: 24018
Val set size: 15784

In [5]:
tpu_failure_log_df = pd.read_hdf(f'{dataset_dir}/'\
                                        f'tpu_failures_{variant}_'\
                                                'combined_preprocessed.h5')

In [6]:
print(f'Anomaly count total: {len(tpu_failure_log_df)}')

tpus_with_failures = np.array(list(set(
                        tpu_failure_log_df.index.get_level_values(1))))

Anomaly count total: 45

In [7]:
tpu_failure_log_df

                   utime  failure_source                     start  \
run    tpu
454322 76016  8433185055         34432.0 2023-06-13 08:16:51+02:00
       76016  8433185010         34432.0 2023-06-13 08:16:42+02:00
454083 59036  3372733888         33792.0 2023-06-10 05:15:44+02:00
       59036  5059100829           640.0 2023-06-10 05:15:43+02:00
       59036  3372733858         33792.0 2023-06-10 05:15:29+02:00
       60017  5059100484           640.0 2023-06-10 05:13:48+02:00
       60017  8431833990         34432.0 2023-06-10 05:13:18+02:00
       60027  8431833890         34432.0 2023-06-10 05:12:58+02:00
       59028  8431833770         34432.0 2023-06-10 05:12:34+02:00
       55022  8431833755         34432.0 2023-06-10 05:12:31+02:00
       55021  8431833755         34432.0 2023-06-10 05:12:31+02:00
       44006  8431700265         34432.0 2023-06-09 21:47:33+02:00
       44006  8431700245         34432.0 2023-06-09 21:47:29+02:00
       44006  8431700145         34432.0 2023-06-09 21:47:09+02:00
       55009  8431467075         34432.0 2023-06-09 08:50:15+02:00
       55009  8431467000         34432.0 2023-06-09 08:50:00+02:00
453858 61023  8430495090         34432.0 2023-06-07 02:50:18+02:00
       61023  8430495015         34432.0 2023-06-07 02:50:03+02:00
       0      5058273147             0.0 2023-06-07 00:37:29+02:00
453816 56024  1686081412           128.0 2023-06-06 21:56:52+02:00
       56024  8430406975         34432.0 2023-06-06 21:56:35+02:00
       60005  1686081255           128.0 2023-06-06 21:54:15+02:00
       56024  1686081225           128.0 2023-06-06 21:53:45+02:00
       61008  8430405985         34432.0 2023-06-06 21:53:17+02:00
       60021  8430405805         34432.0 2023-06-06 21:52:41+02:00
       59027  8430405800         34432.0 2023-06-06 21:52:40+02:00
       60005  1686081155           128.0 2023-06-06 21:52:35+02:00
       56033  8430405740         34432.0 2023-06-06 21:52:28+02:00
       56024  8430405735         34432.0 2023-06-06 21:52:27+02:00
       60024  8430405730         34432.0 2023-06-06 21:52:26+02:00
       60023  8430405730         34432.0 2023-06-06 21:52:26+02:00
       60021  8430405730         34432.0 2023-06-06 21:52:26+02:00
       59027  8430405725         34432.0 2023-06-06 21:52:25+02:00
       59011  8430405720         34432.0 2023-06-06 21:52:24+02:00
       55036  8430405680         34432.0 2023-06-06 21:52:16+02:00
       21024  1686077821           128.0 2023-06-06 20:57:01+02:00
       21024  6744311280         34304.0 2023-06-06 20:57:00+02:00
       21024  8430389025         34432.0 2023-06-06 20:56:45+02:00
       53026  8430364425         34432.0 2023-06-06 19:34:45+02:00
       53026  8430364410         34432.0 2023-06-06 19:34:42+02:00
       53026  8430364370         34432.0 2023-06-06 19:34:34+02:00
       55039  8430263745         34432.0 2023-06-06 13:59:09+02:00
       55039  8430263670         34432.0 2023-06-06 13:58:54+02:00
       60038  8430156955         34432.0 2023-06-06 08:03:11+02:00
       60038  8430156880         34432.0 2023-06-06 08:02:56+02:00

                                   end
run    tpu
454322 76016 2023-06-13 11:09:00+02:00
       76016 2023-06-13 11:09:00+02:00
454083 59036 2023-06-10 05:20:00+02:00
       59036 2023-06-10 05:20:00+02:00
       59036 2023-06-10 05:20:00+02:00
       60017 2023-06-10 05:20:00+02:00
       60017 2023-06-10 05:20:00+02:00
       60027 2023-06-10 05:20:00+02:00
       59028 2023-06-10 05:20:00+02:00
       55022 2023-06-10 05:20:00+02:00
       55021 2023-06-10 05:20:00+02:00
       44006 2023-06-10 05:20:00+02:00
       44006 2023-06-10 05:20:00+02:00
       44006 2023-06-10 05:20:00+02:00
       55009 2023-06-10 05:20:00+02:00
       55009 2023-06-10 05:20:00+02:00
453858 61023 2023-06-07 11:23:00+02:00
       61023 2023-06-07 11:23:00+02:00
       0     2023-06-07 11:23:00+02:00
453816 56024 2023-06-06 22:00:00+02:00
       56024 2023-06-06 22:00:00+02:00
       60005 2023-06-06 22:00:00+02:00
       56024 2023-06-06 22:00:00+02:00
       61008 2023-06-06 22:00:00+02:00
       60021 2023-06-06 22:00:00+02:00
       59027 2023-06-06 22:00:00+02:00
       60005 2023-06-06 22:00:00+02:00
       56033 2023-06-06 22:00:00+02:00
       56024 2023-06-06 22:00:00+02:00
       60024 2023-06-06 22:00:00+02:00
       60023 2023-06-06 22:00:00+02:00
       60021 2023-06-06 22:00:00+02:00
       59027 2023-06-06 22:00:00+02:00
       59011 2023-06-06 22:00:00+02:00
       55036 2023-06-06 22:00:00+02:00
       21024 2023-06-06 22:00:00+02:00
       21024 2023-06-06 22:00:00+02:00
       21024 2023-06-06 22:00:00+02:00
       53026 2023-06-06 22:00:00+02:00
       53026 2023-06-06 22:00:00+02:00
       53026 2023-06-06 22:00:00+02:00
       55039 2023-06-06 22:00:00+02:00
       55039 2023-06-06 22:00:00+02:00
       60038 2023-06-06 22:00:00+02:00
       60038 2023-06-06 22:00:00+02:00

In [8]:
column_names_train = list((train_set_x_df).columns.values)
column_names_test = list((test_set_x_df).columns.values)
column_names_val = list((val_set_x_df).columns.values)

print(f'Channels train: {len(column_names_train)}')
print(f'Channels test: {len(column_names_test)}')
print(f'Channels val: {len(column_names_val)}')

Channels train: 2620
Channels test: 2618
Channels val: 2611

In [9]:
intersection_train_test =\
            np.intersect1d(column_names_train,
                                column_names_test)

intersection_train_val =\
            np.intersect1d(column_names_train,
                                column_names_val) 

intersection_test_val =\
            np.intersect1d(column_names_test,
                                column_names_val) 

print(f'Train/test overlap: {len(intersection_train_test)}')
print(f'Train/val overlap: {len(intersection_train_val)}')
print(f'Test/val overlap: {len(intersection_test_val)}')

Train/test overlap: 2616
Train/val overlap: 2611
Test/val overlap: 2611

In [10]:
nan_amount_train_unlabeled = np.mean(np.sum(pd.isna(train_set_x_df.to_numpy()), 1)/train_set_x_df.shape[1])
nan_amount_test = np.mean(np.sum(pd.isna(test_set_x_df.to_numpy()), 1)/test_set_x_df.shape[1])
nan_amount_val = np.mean(np.sum(pd.isna(val_set_x_df.to_numpy()), 1)/val_set_x_df.shape[1])

print('Mean sparsity original datasets:')
print(f'\tTrain set: {100*nan_amount_train_unlabeled:.3f} %')
print(f'\tTest set: {100*nan_amount_test:.3f} %')
print(f'\tVal set: {100*nan_amount_val:.3f} %')

Mean sparsity original datasets:
	Train set: 0.388 %
	Test set: 0.296 %
	Val set: 0.243 %

In [11]:
train_set_x_df.dropna(axis=0,
                        thresh=50,
                        inplace=True)
    
test_set_x_df.dropna(axis=0,
                        thresh=50,
                        inplace=True)

val_set_x_df.dropna(axis=0,
                        thresh=50,
                        inplace=True)

nan_amount_train_unlabeled = np.mean(np.sum(pd.isna(train_set_x_df.to_numpy()), 1)/train_set_x_df.shape[1])
nan_amount_test = np.mean(np.sum(pd.isna(test_set_x_df.to_numpy()), 1)/test_set_x_df.shape[1])
nan_amount_val = np.mean(np.sum(pd.isna(val_set_x_df.to_numpy()), 1)/val_set_x_df.shape[1])

print('Mean sparsity preprocessed:')
print(f'\tTrain set: {100*nan_amount_train_unlabeled:.3f} %')
print(f'\tTest set: {100*nan_amount_test:.3f} %')
print(f'\tVal set: {100*nan_amount_val:.3f} %')

Mean sparsity preprocessed:
	Train set: 0.386 %
	Test set: 0.296 %
	Val set: 0.243 %

In [12]:
# Should we consider imputation? or changing the threshold in the dropna functions?

In [13]:
def get_tpu_number(channel_name):
    parameters = [int(substring) for substring in re.findall(r'\d+', channel_name)]
    # print(f'{channel_name}: {parameters}')
    return parameters[-1]

In [14]:
tpu_numbers_train = [get_tpu_number(label) for label in column_names_train]
tpu_numbers_test = [get_tpu_number(label) for label in column_names_test]
tpu_numbers_val = [get_tpu_number(label) for label in column_names_val]

tpu_numbers_train_unique = np.array(list(set(tpu_numbers_train)))
tpu_numbers_test_unique = np.array(list(set(tpu_numbers_test)))
tpu_numbers_val_unique = np.array(list(set(tpu_numbers_val)))

rack_numbers_train = np.floor_divide(tpu_numbers_train, 1000)
rack_numbers_test = np.floor_divide(tpu_numbers_test, 1000)
rack_numbers_val = np.floor_divide(tpu_numbers_val, 1000)

In [15]:
racks_train, counts_train =\
    np.unique(rack_numbers_train, return_counts=True)

print('Train set TPUs per rack:')

for rack, count in zip(racks_train, counts_train):
    print(f'{rack}: {count}')

Train set TPUs per rack:
1: 31
2: 31
3: 30
4: 31
5: 31
6: 31
7: 30
8: 31
9: 30
10: 31
11: 31
12: 31
13: 31
17: 31
18: 31
19: 31
20: 31
21: 31
22: 31
23: 31
24: 31
25: 31
26: 31
44: 39
45: 38
46: 39
47: 39
48: 39
49: 39
50: 39
51: 39
52: 39
53: 39
54: 39
55: 39
56: 38
57: 39
58: 36
59: 39
60: 38
61: 37
62: 39
64: 39
65: 38
66: 39
67: 39
68: 37
69: 39
70: 38
71: 39
72: 38
73: 39
74: 37
75: 39
76: 39
77: 39
79: 39
80: 39
81: 38
82: 39
83: 15
84: 39
85: 39
86: 39
87: 39
88: 39
89: 39
90: 39
91: 39
92: 39
93: 39
94: 39
95: 39

In [16]:
racks_test, counts_test =\
    np.unique(rack_numbers_test, return_counts=True)

print('Test set TPUs per rack:')

for rack, count in zip(racks_test, counts_test):
    print(f'{rack}: {count}')

racks_val, counts_val =\
    np.unique(rack_numbers_val, return_counts=True)

print('Val set TPUs per rack:')

for rack, count in zip(racks_val, counts_val):
    print(f'{rack}: {count}')

Test set TPUs per rack:
1: 31
2: 31
3: 30
4: 31
5: 31
6: 31
7: 30
8: 31
9: 30
10: 31
11: 31
12: 31
13: 31
17: 31
18: 31
19: 31
20: 31
21: 30
22: 31
23: 31
24: 31
25: 31
26: 31
44: 39
45: 38
46: 39
47: 39
48: 39
49: 39
50: 39
51: 39
52: 39
53: 38
54: 39
55: 38
56: 39
57: 39
58: 36
59: 39
60: 37
61: 38
62: 39
64: 39
65: 38
66: 39
67: 39
68: 37
69: 39
70: 38
71: 39
72: 38
73: 39
74: 37
75: 39
76: 39
77: 39
79: 39
80: 39
81: 38
82: 39
83: 15
84: 39
85: 39
86: 39
87: 39
88: 39
89: 39
90: 39
91: 39
92: 39
93: 39
94: 39
95: 39
Val set TPUs per rack:
1: 31
2: 31
3: 30
4: 31
5: 31
6: 31
7: 30
8: 31
9: 30
10: 31
11: 31
12: 31
13: 31
17: 31
18: 31
19: 30
20: 31
21: 30
22: 30
23: 31
24: 31
25: 31
26: 31
44: 38
45: 38
46: 39
47: 39
48: 39
49: 39
50: 39
51: 39
52: 39
53: 38
54: 39
55: 37
56: 38
57: 39
58: 36
59: 39
60: 37
61: 37
62: 39
64: 39
65: 38
66: 39
67: 39
68: 37
69: 39
70: 38
71: 39
72: 38
73: 39
74: 37
75: 39
76: 39
77: 39
79: 39
80: 39
81: 38
82: 39
83: 15
84: 39
85: 39
86: 39
87: 39
88: 39
89: 39
90: 39
91: 38
92: 39
93: 39
94: 39
95: 39

In [17]:
print(f'Unique TPUs train set: {len(tpu_numbers_train_unique)}')
print(f'Unique TPUs test set: {len(tpu_numbers_test_unique)}')
print(f'Unique TPUs val set: {len(tpu_numbers_val_unique)}')

Unique TPUs train set: 2620
Unique TPUs test set: 2618
Unique TPUs val set: 2611

In [18]:
exclusive_tpu_numbers_train =\
    np.setdiff1d(tpu_numbers_train_unique,
                    np.union1d(tpu_numbers_test_unique,
                                    tpu_numbers_val_unique))

exclusive_tpu_numbers_test =\
    np.setdiff1d(tpu_numbers_test_unique,
                    np.union1d(tpu_numbers_train_unique,
                                    tpu_numbers_val_unique))

exclusive_tpu_numbers_val =\
    np.setdiff1d(tpu_numbers_val_unique,
                    np.union1d(tpu_numbers_train_unique,
                                    tpu_numbers_test_unique))

print(f'Train set unique TPUs:\n{exclusive_tpu_numbers_train}')
print(f'Test set unique TPUs:\n{exclusive_tpu_numbers_test}')
print(f'Val set unique TPUs:\n{exclusive_tpu_numbers_val}')

Train set unique TPUs:
[21024 53026 55039 60038]
Test set unique TPUs:
[56010 61023]
Val set unique TPUs:
[]

In [19]:
exclusive_tpus_with_failures_train =\
        np.intersect1d(exclusive_tpu_numbers_train,
                                    tpus_with_failures)

exclusive_tpus_with_failures_test =\
        np.intersect1d(exclusive_tpu_numbers_test,
                                    tpus_with_failures)

exclusive_tpus_with_failures_val =\
        np.intersect1d(exclusive_tpu_numbers_val,
                                    tpus_with_failures)

print(f'Exclusive TPUs with failures train:\n{exclusive_tpus_with_failures_train}')
print(f'Exclusive TPUs with failures test:\n{exclusive_tpus_with_failures_test}')
print(f'Exclusive TPUs with failures val:\n{exclusive_tpus_with_failures_val}')

Exclusive TPUs with failures train:
[21024 53026 55039 60038]
Exclusive TPUs with failures test:
[61023]
Exclusive TPUs with failures val:
[]

In [20]:
import math
import re
import argparse
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

In [21]:
def create_channel_names(median_labels, stdev_labels):

    median_labels = ['m_{}'.format(median_label)\
                        for median_label in median_labels]

    stdev_labels = ['std_{}'.format(stdev_label)
                        for stdev_label in stdev_labels]

    labels = np.concatenate((median_labels,
                                stdev_labels))

    return labels

In [22]:
# Reduce dataset

rack_data_train_unlabeled_all = []

columns_reduced_train_unlabeled = None
keys_last = None

train_set_unlabeled_x_df = train_set_x_df

print(f'Train set size total: {len(train_set_x_df)}')

for count, row_x_data in enumerate(tqdm(train_set_unlabeled_x_df.to_numpy(),
                                            desc='Generating unlabeled train set')):

    rack_buckets_data = defaultdict(list)

    for index, datapoint in enumerate(row_x_data):
        rack_buckets_data[rack_numbers_train[index]].append(datapoint)

    rack_median_dcm_rates = {}
    rack_dcm_rate_stdevs = {}

    for rack, rack_bucket in rack_buckets_data.items():
        rack_median_dcm_rates[rack] = np.nanmedian(rack_bucket)
        rack_dcm_rate_stdevs[rack] = np.nanstd(rack_bucket)

    rack_median_dcm_rates = dict(sorted(rack_median_dcm_rates.items()))
    rack_dcm_rate_stdevs = dict(sorted(rack_dcm_rate_stdevs.items()))

    if keys_last != None:
        assert rack_median_dcm_rates.keys() == keys_last,\
                                                'Rack bucket keys changed between slices'

        assert rack_median_dcm_rates.keys() == rack_dcm_rate_stdevs.keys(),\
                                                'Rack bucket keys not identical'

    keys_last = rack_median_dcm_rates.keys()

    if type(columns_reduced_train_unlabeled) == type(None):
        columns_reduced_train_unlabeled = create_channel_names(rack_median_dcm_rates.keys(),
                                                                rack_dcm_rate_stdevs.keys())

    rack_data_np = np.concatenate((np.array(list(rack_median_dcm_rates.values())),
                                        np.array(list(rack_dcm_rate_stdevs.values()))))

    rack_data_train_unlabeled_all.append(rack_data_np)

rack_data_train_unlabeled_all_np = np.stack(rack_data_train_unlabeled_all)
rack_data_train_unlabeled_all_np = np.nan_to_num(rack_data_train_unlabeled_all_np, nan=-1)

nan_amount_train_unlabeled = 100*pd.isna(rack_data_train_unlabeled_all_np.flatten()).sum()/\
                                                        rack_data_train_unlabeled_all_np.size

print('NaN amount reduced train set: {:.3f} %'.format(nan_amount_train_unlabeled))

Train set size total: 56889

Generating unlabeled train set:  85%|██████████████████████████████████████████████████████████████████████████████▉              | 48304/56889 [06:46<01:12, 119.19it/s]/cvmfs/sft.cern.ch/lcg/releases/LCG_104d/numpy/1.23.5/x86_64-el9-gcc13-opt/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1217: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
/cvmfs/sft.cern.ch/lcg/releases/LCG_104d/numpy/1.23.5/x86_64-el9-gcc13-opt/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1878: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
Generating unlabeled train set: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 56889/56889 [07:58<00:00, 118.79it/s]

NaN amount reduced train set: 0.000 %

In [23]:
train_set_unlabeled_x_df = pd.DataFrame(rack_data_train_unlabeled_all_np,
                                                        train_set_unlabeled_x_df.index,
                                                        columns_reduced_train_unlabeled)

In [24]:
train_set_unlabeled_x_df

,m_1,m_2,m_3,m_4,m_5,m_6,m_7,m_8,m_9,m_10,...,std_86,std_87,std_88,std_89,std_90,std_91,std_92,std_93,std_94,std_95
2023-06-06 03:35:55.000935+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-06 03:36:00.000966+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-06 03:36:05.000923+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-06 03:36:10.000913+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-06 03:36:15.000916+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-12 11:10:40.000857+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-12 11:10:45.000892+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-12 11:10:50.000917+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-12 11:10:55.000891+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-12 11:11:00.000881+02:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0